# Generated by Django 5.2.3 on 2025-07-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_newuser_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='profilePic',
            field=models.ImageField(default='images/fallback.png', upload_to='images/'),
        ),
    ]
